---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: build-template
  system: dino-dash
  app: frontend-client
  kind: php
metadata:
  name: build-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: '${APP_NAME}'
      system: dino-dash
      kind: php
    name: '${APP_NAME}'
  spec: {}
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: '${APP_NAME}'
    name: '${APP_NAME}'
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: '${APP_NAME}:${BUILD_TAG}'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: ${GIT_CONTEXT_DIR}
      git:
        ref: ${GIT_BRANCH}
        uri: '${GIT_URL}'
      type: Git
      sourceSecret:
        name: "${SOURCE_SECRET}"
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'php:latest'
          namespace: openshift
      type: Source
    triggers: []
  status: {}
parameters:
- name: APP_NAME
  required: true
  value: frontend-client
- name: GIT_URL
  required: true
  value: https://github.com/cnad-io/ddash-frontend-client.git
- name: GIT_BRANCH
  required: true
  value: master
- name: GIT_CONTEXT_DIR
- name: SOURCE_SECRET
  value: git-auth
- name: BUILD_TAG
  required: true
  value: latest
