---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template
  system: dino-dash
  app: frontend-client
  kind: nodejs
metadata:
  name: deploy-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      system: dino-dash
      app: ${APP_NAME}
      kind: php
    name: ${APP_NAME}
  spec: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      system: dino-dash
      app: ${APP_NAME}
      kind: nodejs
    name: ${APP_NAME}
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      system: dino-dash
      app: ${APP_NAME}
      kind: php
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      system: dino-dash
      app: ${APP_NAME}
      kind: php
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      system: dino-dash
      app: ${APP_NAME}
      kind: php
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${APP_NAME}
  spec:
    paused: true
    revisionHistoryLimit: 10
    replicas: 1
    selector:
      system: dino-dash
      app: ${APP_NAME}
      kind: php
    strategy:
      activeDeadlineSeconds: 21600
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 50Mi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          system: dino-dash
          app: ${APP_NAME}
          kind: php
      spec:
        containers:
        - env: 
            - name: "GAME_ROOM_REMOTE_ADDR"
              value: "${GAME_ROOM_REMOTE_ADDR}"
            - name: "WAITING_ROOM_REMOTE_ADDR"
              value: "${WAITING_ROOM_REMOTE_ADDR}"
          image: ' '
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
  status: {}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: "${PIPELINES_NAMESPACE}"
  userNames:
  - system:serviceaccount:${PIPELINES_NAMESPACE}:${DEPLOYER_USER}
parameters:
- name: CPU_REQUEST
  required: true
  value: 50m
- name: CPU_LIMIT
  required: true
  value: 100m
- name: MEMORY_REQUEST
  required: true
  value: 100Mi
- name: MEMORY_LIMIT
  required: true
  value: 200Mi
- name: APP_NAME
  required: true
  value: frontend-client
- name: PIPELINES_NAMESPACE
  required: true
- name: DEPLOYER_USER
  required: true
  value: jenkins
- name: "GAME_ROOM_REMOTE_ADDR"
  required: true
  value: ""
- name: "WAITING_ROOM_REMOTE_ADDR"
  required: true
  value: "" 